### ISSUE TITLE
[Retail Bug Report] Just doesn't seem to work

### ISSUE THREAD

**Issue by Rumik** [Dreamlogic22/TherapyWeeklyRewards#13] opened 2024-09-26 08:29 UTC
I'm using the latest version of the game. I have the Weekly Rewards plugin displayed on Titan Panel. It is not detecting any progress towards weekly rewards, and clicking on the panel does not open the Great Vault.

![image](https://github.com/user-attachments/assets/02d07d6d-4e8a-405d-9c6e-c0ba54bf8ed7)

**Comment by Dreamlogic22** [comment] 2024-09-26 20:15
@Rumik

Thanks for reporting this issue!  

I can't reproduce the issue on my end.  Silly question time:  Does it show anything if you turn on the map button?  Is your character level 80?

It is very strange that the display is reporting no Catalyst charges in addition to no activity.  If there's nothing to show, it is coded to turn off the tooltip.  

Did the previous version of the addon work for you?

**Comment by Rumik** [comment] 2024-09-27 06:42
Hi there.

My character is level 80. I'm also using the ChoreTracker addon to track the same things and it's working fine.

How do I turn on the map button?

This is the first time I've used the addon. I was looking for a subtler version of ChoreTracker.

Thanks for your time.

**Comment by Dreamlogic22** [comment] 2024-09-27 15:15
You can turn on the map button using the addon options from the main menu (Escape > Options > Addons).  There will be two toggles under "Therapy Weekly Rewards", one to activate the map button and one to lock it.

Please let me know if the map button shows you correct information.  That will help me narrow down what could be going on.

**Comment by Rumik** [comment] 2024-09-28 08:18
Hi again

Both options are disabled, but nothing is showing on the minimap.

Thanks


![Screenshot 2024-09-28 091651 (Large)](https://github.com/user-attachments/assets/5913b42d-6d5d-4657-a21e-3500929f9522)

**Comment by Dreamlogic22** [comment] 2024-09-28 15:43
That is bona fide odd.  

It looks like TWR is properly installed but it is, as you said, not working.  It could be a lots of things, but the most likely suspects are conflicts with another addon or a corrupted addon file.

I am not going to ask you to shut down all addons except TWR because I know how much of a pain it is to figure out which ones are on or off for a particular character thanks to the [addon manager bug](https://github.com/Stanzilla/WoWUIBugs/issues/608) introduced in pre-patch.  I know that a number of yours aren't a problem (Narcissus, Dialog UI, Pawn, Leatrix) because I use them.

Would you mind trying to re-install TWR and see if that helps?  I have a feeling it might not, but it is worth a try.  

If you would like to help me figure out why it is not working in your case, I can put together a release with debug output that will print messages to chat to let us know what in the heck is going on with it.  Does that sound okay, or is this turning into too much work?

You don't see any Lua errors, right?

I apologize for the problems.  I know this is frustrating.  I appreciate your patience.

**Comment by Rumik** [comment] 2024-09-29 08:12
Hi there,

I've tried reinstalling TWR but it made no difference, I've disabled everything except Titan Panel and TWR and it's still not working. More than happy to help figure this out!

I don't see any Lua errors, no.

**Comment by Dreamlogic22** [comment] 2024-09-29 15:13
I believe I found the problem.  

I came to a faulty conclusion about a how and when a poorly-documented Blizzard event fires.  `MYTHIC_PLUS_AFFIX_UPDATE` seemed to be a reasonable broadcast event to check for Great Vault eligibility but it does not appear to fire for every level 80 character.

I will create a test release later today or tomorrow and we can see if it fixes the issue.

Thanks again for reporting this!

**Comment by Dreamlogic22** [comment] 2024-10-01 22:04
Hi there!

I pushed a new version (1.51).  Please let me know if it solves your problem.

**Comment by Rumik** [comment] 2024-10-02 06:51
Hello! 

The message now says "Rewards Available" but that's the only change :(

![Screenshot 2024-10-02 075010 (Large)](https://github.com/user-attachments/assets/f3433fb2-a219-4670-8151-c45714b11253)

**Comment by Rumik** [comment] 2024-10-02 07:22
Weird, it just started working!

![image](https://github.com/user-attachments/assets/046a7e00-3f5e-4a7e-89c7-bcf114e84a99)

**Comment by Dreamlogic22** [comment] 2024-10-02 15:28
That is how it is supposed to work!  

If you have rewards waiting for you in the Great Vault, the display changes to remind you.  Once you collect them, it starts noting your progress again.

I won't close this issue immediately.  Let me know if your display updates properly, but it looks like you are now in business!

The reason you're not seeing a mini-map button is because I haven't added support for the Addon Compartment yet.  It was very buggy when they first released it and I have shied away from messing with it in the meantime.  I'll create an enhancement for that part but as long as you have Titan you should be set.

**Comment by Dreamlogic22** [comment] 2024-10-03 22:12
Thank you once more for reporting this issue and being patient while we figured it out!

Closing this issue as completed.  Please let me know if anything else unexpected happens or if you think of something you would like that makes the display easier to use.

**Closed as completed by Dreamlogic22** 2024-10-03 22:12 UTC
Labels: bug
